"""Human-readable Markdown report from a ``build.json`` summary."""
from __future__ import annotations

from pathlib import Path

from .opt.gear import ARCANA, arcana_choice, enchant_value, per_unit, roll_priorities, title_ranking


def _pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def write_markdown(summary: dict, out_dir: str, extra: dict | None = None) -> str:
    s = summary
    cls = s["class"].capitalize()
    scen = s["scenario"]
    other = [k for k in s["dps"] if k != scen][0]
    pu = per_unit(s["weights"])
    rolls = roll_priorities(pu)
    titles = title_ranking(pu)
    arcana = arcana_choice(pu)
    ench = enchant_value(pu)
    base = s["baseline"]
    L = []
    w = L.append
    w(f"# {cls} — level 45 global build, rotation and macro\n")
    w(f"Generated by `aion2calc` from the global client data (metabot.gg) with Korean data as fallback. "
      f"Primary view: **{scen}** fight (see `docs/methodology.md`). Daevanion budget **{s['daevanion_budget']}** points.\n")
    w("![Build card](images/build_card.png)\n")
    if s.get("objective"):
        objective = s["objective"]
        w(f"## Damage objective: {objective['label']}\n")
        w(f"Score: {objective['score']:,.0f} modeled DPS.\n")
        w(" | ".join(f"{name}: {weight:.0%}, {objective.get('durations', {}).get(name, 'unknown')}s, {objective['components'][name]:,.0f} DPS"
                     for name, weight in objective["weights"].items()) + "\n")
        w(objective["note"] + "\n")
    if s.get("model_note"):
        w(s["model_note"] + "\n")
    if s.get("action_timing"):
        timing = s["action_timing"]
        w("## Outgoing action-time assumptions\n")
        w(timing["note"] + "\n")
        for row in timing["windows"]:
            name = row["name"].replace("\n", " ")
            w(f"- {name}: {row['start_s']:g}–{row['end_s']:g}s.\n")
            req = row.get("skill_requirement")
            if req:
                w(f"  Requested retention: {req['name']} (trained minimum {req['minimum']})" +
                  (f"; supporting effect: {req['effect']}" if req.get("effect") else "") + ".\n")
            else:
                w("  Unlinked timing assumption.\n")
        for name, case in timing["cases"].items():
            w(f"- {name}: {case['paused_s']:g}s unavailable for new actions in {case['duration_s']:g}s; clipped interval union {case['blocks']}.\n")
            for check in case.get("cooldown_checks", []):
                starts = ", ".join(f"{t:g}s" for t in check["activation_starts_s"]) or "none"
                cooldown = check["cooldown_s"]
                gap = check["shortest_reuse_gap_s"]
                status = ("No active action-time windows in this scenario" if not check["activation_starts_s"] else
                          "Cooldown unknown; reuse not assessed" if cooldown is None else
                          f"Assumed effective cooldown {cooldown:g}s; assumed spacing satisfied")
                reuse = "no repeated assumed use" if gap is None else f"shortest reuse gap {gap:g}s"
                mixed = "; largest of differing cooldown assumptions used" if check["mixed_assumptions"] else ""
                w(f"  - {check['skill']}: starts {starts}; {status}; {reuse}{mixed}.\n")
    if s.get("survival"):
        hp = s["survival"]
        w("## HP reserve\n")
        w(f"Crystal-board HP: {hp['selected_node_hp']:,.0f}; minimum {hp['minimum_node_hp']:,.0f}; previous {hp['reference_node_hp']:,.0f}.\n")
        w(hp["note"] + "\n")
        if hp["opponents"]:
            w("| User-assumed encounter/opponent | Required HP | Proxy HP headroom |")
            w("|---|---:|---:|")
            for row in hp["opponents"]:
                name = row["name"].replace("|", " / ").replace("\n", " ")
                w(f"| {name} | {row['required_hp']:,.0f} | {row['headroom_hp']:,.0f} |")
            w("\nHealing timing assumptions (blank duration means the rest of the pressure window):\n")
            for row in hp["opponents"]:
                if "peak_pressure_hp" not in row:
                    continue
                name = row["name"].replace("\n", " ")
                duration = row.get("healing_duration_s")
                duration_label = "rest of window" if duration is None else f"{duration:g}s"
                w(f"- {name}: assumed HPS {row['healing_hps']:g}; delay {row.get('healing_delay_s', 0):g}s; duration {duration_label}; peak ongoing pressure {row.get('peak_pressure_hp', 0):,.0f} HP at {row.get('peak_pressure_at_s', 0):g}s.\n")
            for row in hp["opponents"]:
                if row.get("reductions"):
                    w(f"- Same healing without added reductions: {row['unprotected_required_hp']:,.0f} HP required; assumed reduction {row['assumed_requirement_reduction_hp']:,.0f} HP. Initial hit unchanged; strongest overlap only.\n")
                    for effect in row["reductions"]:
                        label = effect["name"].replace("\n", " ")
                        w(f"  - {label} ({effect['kind']}): assumed {effect['reduction_pct']:g}% pressure reduction from {effect['start_s']:g}s to {effect['end_s']:g}s.\n")
                        req = effect.get("skill_requirement")
                        if req:
                            w(f"    Retained skill: {req['name']} (trained minimum {req['minimum']})" +
                              (f"; supporting effect: {req['effect']}" if req.get("effect") else "") + ".\n")
                        else:
                            w("    Unlinked timing assumption.\n")
            for row in hp["opponents"]:
                for check in row.get("cooldown_checks", []):
                    starts = ", ".join(f"{t:g}s" for t in check["activation_starts_s"]) or "none"
                    cooldown = check["cooldown_s"]
                    gap = check["shortest_reuse_gap_s"]
                    if check["status"] == "no_active_windows":
                        status = "No active reduction windows"
                    elif cooldown is None:
                        status = "Cooldown unknown; reuse not assessed"
                    else:
                        reuse = "no repeated activation" if gap is None else f"shortest reuse gap {gap:g}s"
                        status = f"Assumed effective cooldown {cooldown:g}s; {reuse}; assumed spacing satisfied"
                    mixed = "; largest of differing assumptions used" if check["mixed_assumptions"] else ""
                    w(f"- {row['name']} / {check['skill']}: starts {starts}; {status}{mixed}.\n")
            for row in hp["opponents"]:
                benchmark = row.get("opponent_benchmark")
                if benchmark:
                    context = "; ".join(f"{key}: {value}" for key, value in benchmark.items()).replace("\n", " ")
                    w(f"Optimized opponent benchmark (editable pressure assumption, not measured incoming damage): {context}\n")
                evidence = row.get("recorded_evidence")
                if evidence:
                    context = "; ".join(f"{key}: {value}" for key, value in evidence.items()).replace("\n", " ")
                    w(f"Imported recording context (editable assumption): {context}\n")
        w("DPS is optimized subject to this reserve. Damage-only baselines and stat priorities do not validate survivability.\n")
    if s.get("skill_reserves"):
        reserve = s["skill_reserves"]
        w("## Trained skill reserves\n")
        w(reserve["note"] + "\n")
        for effect in reserve.get("effects", []):
            w(f"- Reserved supporting effect: {effect['skill']} · {effect['text']} (effect Lv {effect['unlock']}); {'retained' if effect['selected'] else 'missing'}.\n")
        for row in reserve.get("effective_levels", []):
            w(f"- {row['name']}: effective Lv {row['selected']} / required {row['minimum']} "
              f"(trained {row['trained']} + Daevanion {row['daevanion']} + fixed bonuses {row['gear']}).\n")
        w("| Skill | Minimum trained level | Selected trained level |")
        w("|---|---:|---:|")
        for row in reserve["skills"]:
            name = row["name"].replace("|", " / ").replace("\n", " ")
            w(f"| {name} | {row['minimum']} | {row['selected']} |")
        w("Reserve met.\n" if reserve["met"] else "Reserve not met.\n")
    if s.get("genus"):
        g = s["genus"]
        w("## Pet Genus Insight\n")
        w(("Saved manual lines included." if g["enabled"] else "Genus scoring disabled.") + "\n")
        w(g["note"] + "\n")
        if g.get("mix"):
            w(g["mix_source"] + ": " + ", ".join(f"{k} {v:.1%}" for k, v in g["mix"].items()) + "\n")
        w("| Genus / slot | Analysis line | Value | DPS contribution | Model status |")
        w("|---|---|---:|---:|---|")
        for row in g["lines"]:
            fields = [f"{row['genus']} / {row['slot']}", row["stat"], row["value"],
                      "—" if row.get("gain") is None else f"{row['gain']:.2%}", row["reason"] or "Included"]
            w("| " + " | ".join(str(x).replace("|", "/").replace("\n", " ").replace("\r", " ") for x in fields) + " |")
        w("")
    w("## Results\n")
    w("| Build | " + scen + " DPS | " + other + " DPS |")
    w("|---|---:|---:|")
    w(f"| **Optimized (this report)** | **{s['dps'][scen]:,.0f}** | **{s['dps'][other]:,.0f}** |")
    w(f"| Typical top global build, optimized rotation | {base['community_optimized_rotation']:,.0f} | {base['community_other_scenario']:,.0f} |")
    w(f"| Typical top global build, default priority | {base['community_naive']:,.0f} | — |")
    gain = s["dps"][scen] / base["community_optimized_rotation"] - 1
    w(f"\nThe optimized build is **{100 * gain:+.1f}%** over the typical top global build played with the same "
      f"rotation optimizer, and **{100 * (s['dps'][scen] / base['community_naive'] - 1):+.1f}%** over that build "
      "played with the default priority. *Typical top global build* = average skill levels, the four most-picked "
      "damage stigmas and the most-picked Daevanion nodes of the top tracked global L45 players of this class "
      "(metabot.gg live data), given the best legal specializations for its levels (specs are not published).\n")

    w("## Rotation (priority list)\n")
    w("Use the highest skill that is ready; the last entry is the filler.\n")
    for i, p in enumerate(s["policy"], 1):
        w(f"{i}. `{p}`")
    w("\n`[sync_de]` = wait for the Delayed Explosion vulnerability window when it is about to be ready; "
      "`[in_ee]` = prefer using it inside Element Enhancement; "
      "`[mp_hi]` = only while MP is at least 60% (weave it in, keep MP for Grace of Enhancement).\n")
    m = s["macro"]
    w("### In-game Skill Macro\n")
    w("Settings → Key Settings → General → Skill Macro. Skill Queue (스킬 예약) **ON**, 10 ms delay on every step, hold the macro key; "
      "manual presses always take priority over the macro.\n")
    w("| Step | Skill |")
    w("|---:|---|")
    for i, st in enumerate(m["steps"], 1):
        w(f"| {i} | {st} |")
    w("\nManual keys (press on cooldown, in this priority): " + (", ".join(m["manual"]) or
      "none — hold the macro key for the whole fight") + "\n")
    w(f"Simulated: this layout reaches **{100 * m['dps_macro'] / m['dps_priority']:.1f}%** of the ideal priority list.\n")
    if m.get("alt_steps"):
        kind = "macro with manual keys" if m.get("alt_manual") else "one-button macro (no manual keys)"
        w(f"**Alternative — {kind}**: macro {' → '.join(m['alt_steps'])}"
          + (f"; manual: {', '.join(m['alt_manual'])}" if m.get("alt_manual") else "")
          + f". Simulated: **{100 * m['dps_alt'] / m['dps_priority']:.1f}%** of the ideal priority list.\n")
    w("### Opener (first 30 s of the simulated fight)\n")
    w("```")
    w(" → ".join(f"{k}@{t:.1f}s" for t, k in s["opener"][:28]))
    w("```\n")

    b = s["build"]
    w("## Skills, specializations and points\n")
    bud = s.get("budgets", {})
    w(f"Skill points used **{b['sp_spent']} / {bud.get('skill', 203)}**, stigma points "
      f"**{b['stigma_spent']} / {bud.get('stigma', 30)}**, "
      f"Daevanion **{b['daevanion_cost']} / {s['daevanion_budget']}**.\n")
    w("| Skill | Trained (SP) | Effective level | Specializations |")
    w("|---|---:|---:|---|")
    eff = b["effective_levels"]
    names = sorted(set(eff) | set(b["sp"]), key=lambda n: -eff.get(n, 1))
    for n in names:
        if n in b["stigmas"]:
            continue
        w(f"| {n} | {b['sp'].get(n, 1)} | {eff.get(n, 1)} | {'; '.join(b['specs'].get(n, [])) or '—'} |")
    w("\n**Stigmas**: " + ", ".join(f"{k} Lv {v}" for k, v in b["stigmas"].items()) + "\n")

    w(f"## Daevanion ({s['daevanion_budget']} points)\n")
    w("![Optimized Daevanion boards](images/daevanion_optimized.png)\n")
    w(f"* Open in metabot planner: {s['links']['metabot_daevanion']}")
    w(f"* Open in gamers4.life planner (KR node values, same node IDs): {s['links']['gamers4life_daevanion']}")
    w(f"* Full skill/stigma/Daevanion build in metabot planner: {s['links']['metabot_build']}\n")
    w("For comparison, the aggregate of the most-picked nodes among top global players:\n")
    w("![Community Daevanion](images/daevanion_community.png)\n")

    w("## Stat priority (simulated)\n")
    w("| Upgrade | DPS gain | Worth in Attack |")
    w("|---|---:|---:|")
    for x in s["weights"]:
        w(f"| {x['label']} | {x['pct']:+.2f}% | {x['attack_equiv'] or 0:.0f} |")
    w("\nAccuracy is a threshold stat (avoid parries; back attacks ignore them) and is not ranked.\n")

    w("## Gear, rolls, enchanting\n")
    lo_lines = (extra or {}).get("gear_lines", [])
    if lo_lines:
        w(f"Loadout: **{(extra or {}).get('loadout_name', 'most common among top global L45 players')}**\n")
        for ln in lo_lines:
            w(f"* {ln}")
        w("")
    wc = (extra or {}).get("weapon_compare")
    if wc:
        w("**Weapon comparison (same build & rotation):**\n")
        w("| Weapon | DPS | vs baseline |")
        w("|---|---:|---:|")
        for row in wc:
            w(f"| {row['name']} | {row['dps']:,.0f} | {100 * row['gain']:+.1f}% |")
        w("")
    w("**Random-roll priority per item** (keep / reroll toward the top of each list):\n")
    for slug in ["rupture-tome", "ludras-grimoire", "spiritforged-guard", "vakron-helm", "bakarma-breastplate",
                 "aulamus-necklace", "aulamus-ring"]:
        if slug in rolls:
            top = ", ".join(f"{r['stat']} ({r['range']})" for r in rolls[slug][:5])
            w(f"* **{slug.replace('-', ' ').title()}**: {top}")
    w("\n**Enchant priority** (DPS per enchant level):\n")
    for r in ench:
        w(f"* {r['slot']}: {r['dps']:.1f} DPS/level")
    w("\n## Titles, arcana, wings, pets\n")
    w("**Best titles by equip bonus** (global client values):\n")
    w("| Title | Grade | Equip bonus | Owned bonus |")
    w("|---|---|---|---|")
    for t in titles[:10]:
        w(f"| {t['name']} ({t['faction']}) | {t['grade']} | {t['equip']} | {t['owned']} |")
    w("\n**Arcana variant per slot** (deity stat that is worth more for this build):\n")
    for slot, a in arcana.items():
        if a.get("tie"):
            w(f"* {slot}: either variant (" + " / ".join(f"{st.capitalize()} +20" for st, _ in
                                                       ARCANA[slot].values()) + ": no damage either way)")
        else:
            w(f"* {slot}: **{a['pick']}** ({a['stat'].capitalize()} +20)")
    ar = s.get("arcana_rolls") or {}
    if ar:
        w("\n**Arcana skill rolls.** Each arcana gives (grade base + enhancement level) random skill levels from "
          "its slot's pool — Rare 2, Legend 3, Unique 4 base rolls, +1 per enhancement level (so a Unique +5 "
          "gives 9); a skill rolled again gains another level, up to the cap. Chalice, Parchment and Compass "
          "roll active skills; Bell and Mirror roll passives.\n")
        w("| Arcana slot | Expected DPS, Unique +0 (4 rolls) | Expected DPS, Unique +5 (9 rolls) | Best rolls (+1 / +2) |")
        w("|---|---:|---:|---|")
        for slot, a in sorted(ar.items(), key=lambda kv: -kv[1]["expected_unique_5"]):
            best = sorted(a["skills"].items(), key=lambda kv: -kv[1][0])[:3]
            bt = ", ".join(f"{n} {g[0]:+.1f}% / {g[1]:+.1f}%" for n, g in best if g)
            w(f"| {slot.capitalize()} | {a['expected_unique_0']:+.1f}% | {a['expected_unique_5']:+.1f}% | {bt} |")
        lv16 = [(n, g) for a in ar.values() for n, g in a["skills"].items()]
        jumps = sorted({n: max(g[i] - (g[i - 1] if i else 0) for i in range(len(g))) for n, g in lv16}.items(),
                       key=lambda kv: -kv[1])[:4]
        w("\nBiggest single-level jumps (usually a specialization unlocking at Lv 16): "
          + ", ".join(f"{n} {v:+.1f}%" for n, v in jumps) + ".\n")
    else:
        w("")
    deity = [x for x in s["weights"] if x["stat"] in ("might", "destruction", "death", "wisdom", "justice",
                                                       "time", "illusion")]
    if deity:
        deity.sort(key=lambda x: -x["pct"])
        w("**Deity (pantheon) stats**, +10 points each (arcana main stats, Abyssal Bracelet rolls, Monolith rewards): "
          + ", ".join(f"{x['label'].split(' +')[0]} {x['pct']:+.2f}%" for x in deity) + ".\n")
    w("**Closet / appearance collection**: every unlocked skin and costume set adds permanent Collection Effect "
      "stats, and wings keep a Retention Effect once owned. The client tables for these are not public, so they "
      "are not itemised here; they are flat stats, so value them with the stat table above and collect the cheap "
      "ones first.\n")
    w("**Wings**: Ultimate Daeva Wings (Accuracy +40, Penetration +500) are the most used and the best "
      "launch option for damage among common wings. **Pets**: pet collection bonuses are mostly genus-specific "
      "(damage vs that monster genus) plus Accuracy/Crit; level the genus of the content you farm first.\n")

    sens = [x for x in (s.get("sensitivity") or []) if x.get("loss_pct") is not None]
    if sens:
        loss = [x["loss_pct"] for x in sens]
        w("## Robustness\n")
        w("Samples with no modeled damage are excluded from percentage losses.\n")
        w(f"Every animation time was randomly perturbed by up to ±25% ({len(sens)} samples) and the rotation "
          f"re-optimized each time. Playing the recommended priority instead of the re-optimized one lost on "
          f"average **{sum(loss) / len(loss):.2f}%** (worst {max(loss):.2f}%).\n")
    cs = s.get("crit_sensitivity")
    if cs:
        a, b = cs["fit"], cs["alt"]
        w("**Crit curve.** The crit-chance curve is fitted to tests at Crit 1048–1326 and extrapolated down to "
          f"launch values: this build sits at **{100 * a['crit_chance']:.1f}%** crit, and Crit +50 ranks "
          f"#{a['crit_rank']} ({a['crit_gain_pct']:+.2f}%). If launch testing shows more crit — e.g. the curve "
          f"shifted to a midpoint of {b['midpoint']:.0f}, giving {100 * b['crit_chance']:.0f}% — Crit +50 becomes "
          f"#{b['crit_rank']} ({b['crit_gain_pct']:+.2f}%). Re-run with `--crit-midpoint` once real numbers exist.\n")
    fid = s.get("kr_fidelity")
    if fid:
        w("## Validation against Korean logs\n")
        w(f"Simulated damage shares (training dummy) overlap **{100 * fid['overlap']:.0f}%** with the mean of the "
          f"top-10 A2DIL Korean dummy logs; {100 * fid['kr_share_not_in_global_data']:.0f}% of the Korean damage "
          "comes from skills that are not in the global level-45 client. Korea plays above level 45 with Lv 16-20 "
          "specializations, so a perfect match is not expected; low values mean the class kit needs hand-tuning "
          "(see `kit/sorcerer.py` for a hand-written kit).\n")
    w("## Sources\n")
    w("* metabot.gg (global client): class skills, Daevanion boards, items, titles, top-player statistics")
    w("* gamers4.life (KR database): skill hit counts, build/Daevanion planners")
    w("* A2DIL (KR training-dummy logs): damage-share validation")
    w("* Inven / Bahamut damage research, aion2ssow calculator: damage formula")
    w("\nSee `docs/methodology.md` for every formula and assumption.\n")
    path = Path(out_dir) / "README.md"
    path.write_text("\n".join(L), encoding="utf-8")
    return str(path)
