"""Human-readable Markdown report from a ``build.json`` summary."""
from __future__ import annotations

import json
from pathlib import Path

from .opt.gear import arcana_choice, enchant_value, per_unit, roll_priorities, title_ranking


def _pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def write_markdown(summary: dict, out_dir: str, extra: dict | None = None) -> str:
    s = summary
    cls = s["class"].capitalize()
    scen = s["scenario"]
    other = [k for k in s["dps"] if k != scen][0]
    pu = per_unit(s["weights"])
    rolls = roll_priorities(pu)
    titles = title_ranking(pu)
    arcana = arcana_choice(pu)
    ench = enchant_value(pu)
    base = s["baseline"]
    L = []
    w = L.append
    w(f"# {cls} — level 45 global build, rotation and macro\n")
    w(f"Generated by `aion2calc` from the global client data (metabot.gg) with Korean data as fallback. "
      f"Objective: **{scen}** fight (see `docs/methodology.md`). Daevanion budget **{s['daevanion_budget']}** points.\n")
    w("![Build card](images/build_card.png)\n")
    w("## Results\n")
    w("| Build | " + scen + " DPS | " + other + " DPS |")
    w("|---|---:|---:|")
    w(f"| **Optimized (this report)** | **{s['dps'][scen]:,.0f}** | **{s['dps'][other]:,.0f}** |")
    w(f"| Global most-common build, optimized rotation | {base['community_optimized_rotation']:,.0f} | {base['community_other_scenario']:,.0f} |")
    w(f"| Global most-common build, naive priority | {base['community_naive']:,.0f} | — |")
    gain = s["dps"][scen] / base["community_optimized_rotation"] - 1
    w(f"\nThe optimized build is **{100 * gain:+.1f}%** over the most common global top-player build "
      f"played with the same rotation optimizer, and "
      f"**{100 * (s['dps'][scen] / base['community_naive'] - 1):+.1f}%** over that build played with a naive priority.\n")

    w("## Rotation (priority list)\n")
    w("Use the highest skill that is ready; the last entry is the filler.\n")
    for i, p in enumerate(s["policy"], 1):
        w(f"{i}. `{p}`")
    w("\n`[sync_de]` = wait for the Delayed Explosion vulnerability window when it is about to be ready; "
      "`[in_ee]` = prefer using it inside Element Enhancement.\n")
    m = s["macro"]
    w("### In-game Skill Macro\n")
    w("Settings → Key Settings → General → Skill Macro. Skill Queue (스킬 예약) **ON**, 10 ms delay on every step, hold the macro key; "
      "manual presses always take priority over the macro.\n")
    w("| Step | Skill |")
    w("|---:|---|")
    for i, st in enumerate(m["steps"], 1):
        w(f"| {i} | {st} |")
    w(f"\nManual keys (press on cooldown, in this priority): {', '.join(m['manual'])}\n")
    w(f"Simulated: the macro + manual keys reach **{100 * m['dps_macro'] / m['dps_priority']:.1f}%** of the ideal priority list.\n")
    w("### Opener (first 30 s of the simulated fight)\n")
    w("```")
    w(" → ".join(f"{k}@{t:.1f}s" for t, k in s["opener"][:28]))
    w("```\n")

    b = s["build"]
    w("## Skills, specializations and points\n")
    w(f"Skill points used **{b['sp_spent']} / 203**, stigma points **{b['stigma_spent']} / 30**, "
      f"Daevanion **{b['daevanion_cost']} / {s['daevanion_budget']}**.\n")
    w("| Skill | Trained (SP) | Effective level | Specializations |")
    w("|---|---:|---:|---|")
    eff = b["effective_levels"]
    names = sorted(set(eff) | set(b["sp"]), key=lambda n: -eff.get(n, 1))
    for n in names:
        if n in b["stigmas"]:
            continue
        w(f"| {n} | {b['sp'].get(n, 1)} | {eff.get(n, 1)} | {'; '.join(b['specs'].get(n, [])) or '—'} |")
    w("\n**Stigmas**: " + ", ".join(f"{k} Lv {v}" for k, v in b["stigmas"].items()) + "\n")

    w(f"## Daevanion ({s['daevanion_budget']} points)\n")
    w("![Optimized Daevanion boards](images/daevanion_optimized.png)\n")
    w(f"* Open in metabot planner: {s['links']['metabot_daevanion']}")
    w(f"* Open in gamers4.life planner (KR node values, same node IDs): {s['links']['gamers4life_daevanion']}")
    w(f"* Full skill/stigma/Daevanion build in metabot planner: {s['links']['metabot_build']}\n")
    w("For comparison, the aggregate of the most-picked nodes among top global players:\n")
    w("![Community Daevanion](images/daevanion_community.png)\n")

    w("## Stat priority (simulated)\n")
    w("| Upgrade | DPS gain | Worth in Attack |")
    w("|---|---:|---:|")
    for x in s["weights"]:
        w(f"| {x['label']} | {x['pct']:+.2f}% | {x['attack_equiv'] or 0:.0f} |")
    w("\nAccuracy is a threshold stat (avoid parries; back attacks ignore them) and is not ranked.\n")

    w("## Gear, rolls, enchanting\n")
    lo_lines = (extra or {}).get("gear_lines", [])
    if lo_lines:
        w(f"Loadout: **{(extra or {}).get('loadout_name', 'most common among top global L45 players')}**\n")
        for ln in lo_lines:
            w(f"* {ln}")
        w("")
    wc = (extra or {}).get("weapon_compare")
    if wc:
        w("**Weapon comparison (same build & rotation):**\n")
        w("| Weapon | DPS | vs baseline |")
        w("|---|---:|---:|")
        for row in wc:
            w(f"| {row['name']} | {row['dps']:,.0f} | {100 * row['gain']:+.1f}% |")
        w("")
    w("**Random-roll priority per item** (keep / reroll toward the top of each list):\n")
    for slug in ["rupture-tome", "ludras-grimoire", "spiritforged-guard", "vakron-helm", "bakarma-breastplate",
                 "aulamus-necklace", "aulamus-ring"]:
        if slug in rolls:
            top = ", ".join(f"{r['stat']} ({r['range']})" for r in rolls[slug][:5])
            w(f"* **{slug.replace('-', ' ').title()}**: {top}")
    w("\n**Enchant priority** (DPS per enchant level):\n")
    for r in ench:
        w(f"* {r['slot']}: {r['dps']:.1f} DPS/level")
    w("\n## Titles, arcana, wings, pets\n")
    w("**Best titles by equip bonus** (global client values):\n")
    w("| Title | Grade | Equip bonus | Owned bonus |")
    w("|---|---|---|---|")
    for t in titles[:10]:
        w(f"| {t['name']} ({t['faction']}) | {t['grade']} | {t['equip']} | {t['owned']} |")
    w("\n**Arcana variant per slot** (deity stat that is worth more for this build):\n")
    for slot, a in arcana.items():
        w(f"* {slot}: **{a['pick']}** ({a['stat'].capitalize()} +20)")
    asv = s.get("arcana_skill_values") or []
    if asv:
        w("\n**Arcana random skill option** (Unique arcana roll one option from the class pool when soul-bound, "
          "up to +4; simulated DPS gain on this build):\n")
        w("| Skill | +1 | +2 | +3 | +4 |")
        w("|---|---:|---:|---:|---:|")
        for r in asv:
            w(f"| {r['skill']} | " + " | ".join(f"{g:+.2f}%" for g in r["gain_pct"]) + " |")
        w("\nThe pool holds passives only, so at level 45 an active skill still stops at Lv 14 "
          "(10 from skill points + 4 Daevanion nodes); the Lv 16 specialization options are out of reach.\n")
    else:
        w("")
    w("**Wings**: Ultimate Daeva Wings (Accuracy +40, Penetration +500) are the most used and the best "
      "launch option for damage among common wings. **Pets**: pet collection bonuses are mostly genus-specific "
      "(damage vs that monster genus) plus Accuracy/Crit; level the genus of the content you farm first.\n")

    sens = s.get("sensitivity") or []
    if sens:
        loss = [x["loss_pct"] for x in sens]
        w("## Robustness\n")
        w(f"Every animation time was randomly perturbed by up to ±25% ({len(sens)} samples) and the rotation "
          f"re-optimized each time. Playing the recommended priority instead of the re-optimized one lost on "
          f"average **{sum(loss) / len(loss):.2f}%** (worst {max(loss):.2f}%).\n")
    w("## Sources\n")
    w("* metabot.gg (global client): class skills, Daevanion boards, items, titles, top-player statistics")
    w("* gamers4.life (KR database): skill hit counts, build/Daevanion planners")
    w("* A2DIL (KR training-dummy logs): damage-share validation")
    w("* Inven / Bahamut damage research, aion2ssow calculator: damage formula")
    w("\nSee `docs/methodology.md` for every formula and assumption.\n")
    path = Path(out_dir) / "README.md"
    path.write_text("\n".join(L), encoding="utf-8")
    return str(path)
